# Generated by Django 4.1.3 on 2023-03-18 08:53

from django.db import migrations, models
import fashion_titans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=120)),
                ('img', models.ImageField(blank=True, default=True, null=True, upload_to=fashion_titans.models.upload_path_category)),
                ('desc', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
