# Generated by Django 4.1.3 on 2023-03-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fashion_titans", "0002_recmd"),
    ]

    operations = [
        migrations.CreateModel(
            name="recmd1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(default="pattern", max_length=50)),
                ("predection", models.CharField(default="pattern", max_length=50)),
                ("img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
